### PR TITLE
Adding ANGLE support for the upstream Mupen Libretro Core. Currently …

### PR DESCRIPTION
**Pull request by JustMeDaFaq**
…primary used for XBox One/Series S/X.

### CODE REVIEW

**Comment by m4xw** [comment]
That PR wont do, lemme point you here tho https://github.com/libretro/mupen64plus-libretro-nx/commit/ded692e3a3abb4a54971ea9ee3a2d82d61fa42dc (angle_testing branch)
Just needs a rebase and angle defines, your pr as-is, won't even run

**Comment by JustMeDaFaq** [comment]
Thanks, yeah, wasnt supposed to be here. Sorry for the hassle. 
It works tho, builds are successfull with running make HAVE_ANGLE=1 and the proper angle files at the correct location :)

**Comment by m4xw** [comment]
It will crash at runtime, unless that was fixed in the log cb?

**Comment by JustMeDaFaq** [comment]
Unsure, played 45min of SM64 without issues tho. Both seemed to work on first sight, GlideN64 and Angrylion. 
Definetly wouldve need more testing, wasnt supposed to be pushed here.

**Pull request closed without merging**
