### PR TITLE
Add LLE settings.

### PR DESCRIPTION
**Pull request by mudlord**
Start importing of settings.

Haven't worked out yet how to distinguish between the two render plugins.

Why not have a selection to pick each plugin and then it picks the right RSPs accordingly?

### CODE REVIEW

**Comment by m4xw** [comment]
> Why not have a selection to pick each plugin and then it picks the right RSPs accordingly?

That was the plan, show core options depending on RSP/RDP selection, anyway 5am soon so will check that over the weekend.
You might need to remind me ;)

**Comment by mudlord** [comment]
Thats a good idea, but I am wondering does the libretro API allow for such things?

Or will it need to be on RetroArch's side?

**Comment by m4xw** [comment]
It needs to have the same amount of options, then we could do it (swap them on the fly)

**Comment by m4xw** [comment]
merged for now, the branch is not used anywhere yet, so we can figure something later.

**Pull request merged**
