### PR TITLE
Port build fix for RPI from mupen64plus-libretro

### PR DESCRIPTION
**Pull request by hhromic**
Consolidates fixes from the following pull requests:

* RPI: use new vendor library names
  https://github.com/libretro/mupen64plus-libretro/pull/39

* fix makefile for the raspberry pi
  https://github.com/libretro/mupen64plus-libretro/pull/73

I made an experimental module to compile `mupen64plus-next` in RetroPie. It works like a charm, great work on this core! However, as discussed before, the patch to use the new vendor library names and also a small fix to the Makefile (explained on the second refd PR) are needed for it compile correctly. This PR addresses back-porting these patches from the old core. Because this core uses an updated mupen64plus-core, some parts of the original patch aren't required anymore.

As feedback, the core runs pretty nicely on a non-overclocked stock Raspberry Pi 3B+. I tested a number of games and beyond the usual glitches, I think this core works >= the older `mupen64plus` core. Looks like this core is a promising replacement indeed. Some games I feel run better.

If you merge this PR, and if you desire, I can coordinate the experimental scriptmodule to install this core in the RetroPie forums, therefore users from that platform can also test and provide feedback for future development.

Thanks for the work on this core, looking very promising!

### CODE REVIEW

**Comment by m4xw** [comment]
Heh, thanks for the PR, does it use the dynamic recompiler (as in auto-detection works)?
GlideN64 3.0 update is on its way btw ;)

**Comment by m4xw** [comment]
So the raspberry is still stuck with 32bit?
That's a shame in my eyes.
Yes it needs at least a 64bit kernel and also needs 64bit RA.

**Comment by hhromic** [comment]
I now just tested simply with:

    make platform=rpi3

And a dynarec is autodetected too `-DNEW_DYNAREC=3`:

    cc -O2 -DNDEBUG -fsigned-char -ffast-math -fno-strict-aliasing -fomit-frame-pointer -fvisibility=hidden  -DGIT_VERSION=\"" e56c935"\" -DOS_LINUX -I./mupen64plus-core/subprojects/md5 -I./mupen64plus-core/subprojects/minizip -I./mupen64plus-core/subprojects/xxhash -DHAVE_NEON -D__ARM_NEON__ -D__NEON_OPT -ftree-vectorize -mvectorize-with-neon-quad -ftree-vectorizer-verbose=2 -funsafe-math-optimizations -fno-finite-math-only -D__LIBRETRO__ -DUSE_FILE32API -DM64P_PLUGIN_API -DM64P_CORE_PROTOTYPES -D_ENDUSER_RELEASE -DSINC_LOWER_QUALITY -DTXFILTER_LIB -D__VEC4_OPT -DMUPENPLUSAPI  -I/opt/vc/include -I/opt/vc/include/interface/vcos -I/opt/vc/include/interface/vcos/pthreads -I./custom -I./custom/mupen64plus-core -I./custom/android/include -I./custom/GLideN64 -I./GLideN64/src -I./GLideN64/src/osal -I./mupen64plus-core/src -I./mupen64plus-core/src/api -I./custom/mupen64plus-core/plugin/audio_libretro -I./libretro-common/include -I./libretro -I./GLideN64/src/inc -I./xxHash  -fPIC  -DVC -march=armv8-a+crc -mtune=cortex-a53 -mfpu=neon-fp-armv8 -mfloat-abi=hard  -DHAVE_OPENGLES -DHAVE_OPENGLES2 -DGLES2 -DUSE_DEPTH_RENDERBUFFER  -DNEW_DYNAREC=3 -DDYNAREC -I./mupen64plus-core/src/asm_defines/ -c libretro-common/audio/resampler/drivers/sinc_resampler_neon.S -o libretro-common/audio/resampler/drivers/sinc_resampler_neon.o

However if I force with `aarch64`:

    make platform=rpi3 WITH_DYNAREC=aarch64

It doesn't build because it can't link the 64 bits assembler:
```
mupen64plus-core/src/device/r4300/new_dynarec/arm64/linkage_arm64.S: Assembler messages:
mupen64plus-core/src/device/r4300/new_dynarec/arm64/linkage_arm64.S:80: Error: ARM register expected -- `mov w0,w1'
mupen64plus-core/src/device/r4300/new_dynarec/arm64/linkage_arm64.S:84: Error: ARM register expected -- `mov w0,w2'
mupen64plus-core/src/device/r4300/new_dynarec/arm64/linkage_arm64.S:88: Error: ARM register expected -- `mov w0,w3'
mupen64plus-core/src/device/r4300/new_dynarec/arm64/linkage_arm64.S:92: Error: ARM register expected -- `mov w0,w4'
  (and more)
```

So I guess this won't work until the RPI is run in 64 bits mode.

**Comment by m4xw** [comment]
I will go ahead and merge it then, but it might be worth checking out the 64bit version, since we slowly start giving more attention to the aarch64 development.

**Comment by hhromic** [comment]
> So the raspberry is still stuck with 32bit?

Yes, the RPI foundation has no intention on porting Raspbian to 64 bits at the moment :(
And because RetroPie probably will always be based on Raspbian, won't get 32 bits any time soon.

> That's a shame in my eyes.
> Yes it needs at least a 64bit kernel and also needs 64bit RA.

Then I guess the new dynarec for the RPI will have better luck with Lakka (not sure if they build for the RPI with 64 bits) or other specific-purpose distributions.

Just curious, the "old" dynarec won't get any more further work than in the base mupen64plus ?

**Comment by m4xw** [comment]
@hhromic Also i'd love to get this on RetroPie, so you have my support ;)
I will add Raspberry aarch32 as supported platform

**Comment by m4xw** [comment]
@hhromic the old and new dynarec are both maintained, but there is still room for improvement for the aarch64 one and I am sure it will surpass the aarch32(armv7) dynarec

**Comment by hhromic** [comment]
That's great to hear!  I guess for now the biggest benefit in the near future will be the constant updates form upstream to mupen64plus-core and gliden64. I will soon post a scriptmodule to install this core in the RetroPie forums. Thanks for merging this PR, makes the scriptmodule simpler :)

And again, thank you a lot for your work on this core.

**Pull request merged**
