### PR TITLE
Add CBFD overload filter emulation.

### PR DESCRIPTION
**Pull request by mudlord**
Update to most recent HLE RSP.

https://github.com/mupen64plus/mupen64plus-rsp-hle/commit/27580a8c33f0d66fa2f02582d45975f23fe2b1aa

### CODE REVIEW

**Comment by m4xw** [comment]
Will need to pull the subrepo, cant just pick the commit.
Gonna leave this open as reminder, currently a bit absent from this but will get to it shortly

**Comment by mudlord** [comment]
Right, completely forgot about that. Didn't realize the RSP was so out of date.

**Comment by m4xw** [comment]
https://github.com/libretro/mupen64plus-rsp-hle/commits/master

For the most part it were unrelated commits so there was nothing of interest

**Comment by mudlord** [comment]
Oh okay, I see the parallel-n64 situation is pretty dire. I am not opposed to working on that though to try to bring it up to some semblance of uptodateness.

Main thing I see is the lack of HWFBE but there is some things from the bits in there that can be salvaged. Take for instance in Rice processing 2 pixels at once (why not use SSE there? Guess Rice himself didn't wanna use MMX at the time there). Not sure about Glide64 since it relies on power of two textures and all sorts of Glide specific limits.

**Comment by m4xw** [comment]
Pulled

**Pull request closed without merging**
