### PR TITLE
Added core option: ForceDisableExtraMem

### PR DESCRIPTION
**Pull request by RiskyJumps**
I added a core option for disabling extra memory, according to given requirements.

### CODE REVIEW

**Comment by m4xw** [comment]
Thanks

**Comment by RiskyJumps** [comment]
Thanks to you for your time.

**Comment by hhromic** [comment]
Hi guys, sorry for the late comment :)

What is the difference between setting this new option to `true` vs setting all/any existing `pX-pak` options to `none` or any non-`memory` value ?

**Comment by hhromic** [comment]
Ah you are right, forgot there was a RAM expansion module != controller memory pack. My bad! :)

**Pull request merged**
