### PR TITLE
Modern G++ now needs stdexcept

### PR DESCRIPTION
**Pull request by cruduxcru0**
Fixes compiling on newest GCC under MSYS2.

### CODE REVIEW

**Comment by kivutar** [comment]
I confirm I need this even to build on Linux

**Comment by bslenul** [comment]
I also have to add `#include <cstdint>` in rsp_disasm.hpp personally, or else I'm getting some `'uint32_t' was not declared in this scope` errors during build.

**Comment by cruduxcru0** [comment]
Correct, thats needed too.

**Comment by Sanaki** [comment]
Duplicate of #491

**Comment by m4xw** [comment]
Closing in favor of 491

**Pull request closed without merging**
