### PR TITLE
Enable angrylion on macos/ios/tvos

### PR DESCRIPTION
**Pull request by warmenhoven**

### CODE REVIEW

**Comment by kerberjg** [comment]
I don't think it's working. Just installed the latest RetroArch Nightly (2024-01-06), with Mupen64 core 9dd7459 (same commit as above merge), and while the config says Angrylion is enabled (tried manually saving config and restarting app), it's still rendering using GlideN64.

For context, tvOS version is 17.2, I'm using the latest Apple TV model (A2843).

Let me know if there's anything I can do to help troubleshoot this

**Comment by warmenhoven** [comment]
Hm, it's working on Mac and I have heard from one other person it's working on tvOS, but I'll double check again soon.

**Comment by warmenhoven** [comment]
Oh, I see what is the matter. If the JIT isn't enabled it will force GLideN64.

**Comment by warmenhoven** [comment]
Sorry, the earlier comment was with my other PR (https://github.com/libretro/mupen64plus-libretro-nx/pull/490) applied. I tried it again without that PR and yes, on iOS and tvOS it falls back to GLideN64 because only the HLE RSP plugin is available. So I've created another PR (https://github.com/libretro/mupen64plus-libretro-nx/pull/511) to enable the CXD4 LLE RSP plugin, which doesn't require a JIT.

**Comment by kerberjg** [comment]
Nice, thanks for taking a look at it! 😊
I hope these get merged in soon ✨

**Pull request merged**
