### PR TITLE
Fix F-Zero X Expansion Kit cartridge hack by using F-Zero X microcode

### PR DESCRIPTION
**Pull request by dmrlawson**
Made against this project as requested.

As far as I know it needs to be treated the same as regular F-Zero X, so this change ensures that.

### CODE REVIEW

**Comment by dmrlawson** [comment]
How come?

**Comment by m4xw** [comment]
@dmrlawson It got autoclosed because I merged the branch, didn't close it on purpose.
Like I said tho, it should still use the efz func and we should return -1 in the fallback codepath.

**Comment by m4xw** [comment]
.. Also I should point out I don't want to make the change as is, because I will totally forget about it and then wonder why LLE fallback isn't working once implemented, lol.
You very first suggestion in Discord was acceptable, now that I know the usage of the func.
Hope you don't mind.

**Comment by dmrlawson** [comment]
Ah, fair enough.

My understanding is that returning `-1` from the `HleForwardTask` thing means that it will use LLE in a number of different places, killing performance. There's no need to use it for F-Zero X Expansion because afaik it's the same ucode as F-Zero X.

Have I misunderstood something somewhere?

**Comment by dmrlawson** [comment]
Or maybe I'm totally misunderstanding and the reason that function gets hit is that the microcode _is_ different, but sufficiently similar that it mostly works

**Comment by m4xw** [comment]
-1 should mean LLE Fallback is not implemented
0 should mean forwarded to LLE RSP.
At least from the quotes that I saw.

**Comment by m4xw** [comment]
(Basically just restore some code I nuked long ago)

**Comment by dmrlawson** [comment]
If that's the case, how is it working currently when LLE is not implemented? That function is checked in a few different places (although maybe only when other options have been exhausted?)

**Comment by m4xw** [comment]
As you can see its not working.
It thinks RSP command was forwarded while it only got ignored.

**Comment by dmrlawson** [comment]
Sorry - I mean with other, standard games

**Comment by m4xw** [comment]
Almost all ucodes are implemented in the HLE RSP.
So it almost never happens to begin with.

**Pull request closed without merging**
