### PR TITLE
Improve fullspeed overclock

### PR DESCRIPTION
**Pull request by carnivoroussociety**
This hack applies a constant for count register calculation (dynamic compiler core).

This improves performance in many titles such as GoldenEye, Perfect Dark, Conker's Bad Fur Day, Indiana Jones, Re-Volt.

### CODE REVIEW

**Comment by m4xw** [comment]
Did a quick test, seems to perform decently.
I will take my time testing this tho, so don't expect it _too_ quickly.
Thanks.

**Comment by HappehLemons** [comment]
This is great news. I'd be happy to test this on the N64 library if you're able to provide a build & report any issues if you're looking for that type of testing.

**Comment by m4xw** [comment]
https://git.m4xw.net/libretro/cores/mupen64plus-libretro-nx/-/pipelines/5299/builds

**Comment by m4xw** [comment]
Didn't forget about this

**Comment by m4xw** [comment]
I will include it when I finish my Glide branch & improved broken-romhack support.

**Comment by m4xw** [comment]
Btw there would be interest having this in upstream mupen as well if this can work out of the interpreter impl (but from a quick look it seems we got lucky it works out this way)

**Comment by carnivoroussociety** [comment]
Originally I did get this logic working with the other cores and I'm happy to migrate these changes upstream, which repro is it?

**Comment by m4xw** [comment]
I talk about https://github.com/mupen64plus/mupen64plus-core , but they would only accept it if it works for interpreter as well in some way

**Comment by carnivoroussociety** [comment]
As per Logan's suggestion, the calculation has changed to using shift difference. This provides a granular level of adjustment to the overclock and generally more stable than using a constant value.

**Comment by m4xw** [comment]
Btw its best to hold off changes for now.
I have the mupen core rebase done (still needs some cleanup) and i need it to work with netplay as well :)
So to spare u from doing some redundant work.. I will ping u when i got it merged the next days (hopefully, netplay will need more work tho due to the lobby system)

**Comment by KMFDManic** [comment]
@carnivoroussociety Very cool with the Overclock accessibility.  I tried compiling your branch and generated this error.  Note: I can compile the main branches without error.  It would absolutely rock if you were able to determine what is causing the failure.  I am attempting to do it for arm.

```mupen64plus-core/src/main/main.c:1036:24: error: 'OverclockFactor' undeclared (first use in this function)
     overclock_factor = OverclockFactor;
                        ^
mupen64plus-core/src/main/main.c:1036:24: note: each undeclared identifier is reported only once for each function it appears in
make: *** [Makefile:545: mupen64plus-core/src/main/main.o] Error 1```

**Comment by carnivoroussociety** [comment]
A far better overclock has been submitted upstream. Please use this when possible instead https://github.com/mupen64plus/mupen64plus-core/pull/789

**Comment by m4xw** [comment]
I am aware, will get this in as soon upstream got merged! ;)

**Comment by m4xw** [comment]
Yea i noticed it a few minutes afterwards ;)
Didn't get around pulling in upstream code yet but its on my todo!
Congratulations ;)

**Comment by m4xw** [comment]
@carnivoroussociety better late then never, its finally in!

**Comment by carnivoroussociety** [comment]
Thank you for the welcoming news, much appreciated.

**Pull request closed without merging**
