### PR TITLE
Added support for tvOS

### PR DESCRIPTION
**Pull request by doctor-amaton**
Hi!

I tested the core on tvOS 14.4, Apple TV HD (4th generation).
It seems to work correctly (tested Super Mario 64).

You might notice I'm just using the same config as iOS too.

Thanks!

PS: Sorry about the trailing white space that my editor removed

### CODE REVIEW

**Comment by twinaphex** [comment]
Looks OK to merge to me @m4xw.

**Comment by m4xw** [comment]
Is https://github.com/libretro/mupen64plus-libretro-nx/issues/219 a issue?

**Comment by doctor-amaton** [comment]
> Is #219 a issue?

Yes, after some deeper testing, the Yoshi's Story black texture issue is present on tvOS too, as well as similar Mario Kart 64 problems...

**Comment by m4xw** [comment]
Hope = crushed. I'd like to unify the ios-arm64 changes in .common to some HAVE_EGL flag before I merge.
Theres also further mac changes in https://github.com/libretro/mupen64plus-libretro-nx/pull/286/files that you might want to evaluate & include. That will also superseed #256

**Comment by m4xw** [comment]
Might wanna try my ios branch changes and see if that resolves it

**Comment by m4xw** [comment]
whats the state of it? Worth a rebase and test. If it works nicely i add

**Comment by kerberjg** [comment]
tvOS support was merged in with #482, is there anything extra in this PR?

**Pull request closed without merging**
