### PR TITLE
IOS Support + Embedd Dependencies

### PR DESCRIPTION
**Pull request by m4xw**

### CODE REVIEW

**Comment by m4xw** [comment]
Still need to remove -lz from linking, I guess I will ignore it being no subrepo after all, at least for the time being.
Will probably do a little final rebase / amend before merge.

@jet082 I will add you as co-author for the IOS port commit.

**Comment by m4xw** [comment]
@estefan3112 Do you have a xcode installed?

**Comment by estefan3112** [comment]
Yes I do, latest version. I am signing Retroarch with my own developer account (without being a developer) for my iPad 😀

**Comment by m4xw** [comment]
I have a dev acc but no env :P
I am looking at fixing ios aarch64 build, want to look at the ios branch and see whats needed?
This would help a ton, armv7 builds are already working for it so should be simple..

**Comment by estefan3112** [comment]
Wow I will try my best 😬😅

**Comment by estefan3112** [comment]
PS may I ask for your help via Discord (already there)?

**Comment by m4xw** [comment]
@estefan3112 yes m4xw#1560, am on libretro discord and retronx.
contact me as needed.

**Pull request merged**
